### ISSUE TITLE
Incrementing the progress bar does not work

### ISSUE THREAD

**Issue by dweemx** [cturbelin/redisProgress#1]
Hi,
I'm trying to update the progress bar using:
```
progress$incr()
```
But this leads me to:
```
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  ERR hash value is not an integer
```

The only way I found to update the progression is using:
```
progress$step(newvalue = progress$value()+1)
```
But this does not update my progress bar in the right way.

Any idea what the problem could be?

**Comment by cturbelin** [comment]
Thank you !
I found it is a serializing problem with some driver.
If you were using rredis driver it was because the increment need to use a raw value instead of the serialized value stored by rredis. I've just updated the repo to fix this.
The problem doesnt happen with redux backend (it's not tested yet with RcppRedis)
Best
